version: "3.9"

services:
  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./www:/var/www/html          # ✅ единый путь
      - ./default.conf:/etc/nginx/conf.d/default.conf
    # НЕ используйте ./code — он не нужен

  php:
    image: php:8.2-fpm
    container_name: lab2_php
    volumes:
      - ./www:/var/www/html          # ✅ тот же путь
    expose:
      - "9000"
    command: ["php-fpm", "-R", "-O"]  # включить TCP на 9000

